### ISSUE TITLE
Rely on/add compiled styles to package instead of less

### ISSUE THREAD

**Issue by joeyfigaro** [whoisandie/react-rangeslider#44] opened 2017-02-11 19:07 UTC
Initially, I thought I was running into errors because I didn't have the appropriate loaders in webpack, but now it's looking like `./rangeslider.less` doesn't exist.

**Comment by whoisandie** [comment] 2017-02-12 17:16
Duplicate of #43

**Closed by whoisandie** 2017-02-12 17:16 UTC
